spring:

  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=true

    username: daangn
    password: daangn1118

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379
    password: daangn1118
